### ISSUE TITLE
Support multipart/byteranges for requests?

### ISSUE THREAD

**Issue by tomaka** [frewsxcv/tiny-http#19]

**Comment by cybergeek94** [comment]
I was in the middle of implementing support for this crate in [`multipart`](https://github.com/cybergeek94/multipart) when I noticed the header parsing code is incomplete. It will ignore the `boundary` param in the `Content-Type` header, as it's only expecting `q={float}`:

    Content-Type: multipart/form-data; boundary=asdf1234

I'm not sure what the story is on headers for this crate as it looks like it's wanting to move to strongly typed headers, but getting the boundary is necessary for multipart request body parsing to work.

**Comment by tomaka** [comment]
Moving to strongly typed headers is just a suggestion. Nothing has been done to move towards this.

If I remember correctly the headers that are returned by `get_headers` are "raw", without any parsing.
There is a function that parses content-type-like headers, but it is only used to choose which transfer encoding to use in the response.
