### ISSUE TITLE
spins using 100% CPU

### ISSUE THREAD

**Issue by MarkSwanson** [frewsxcv/tiny-http#54]
The default example provided in the README.md file uses 100% CPU after serving a single request.
It shouldn't be using any CPU as I only sent it a single request.

**Comment by tomaka** [comment]
It's weird. In Firefox it happens only if you do Ctrl+F5 instead of F5 alone.

**Comment by tomaka** [comment]
So what happened is that when a connection was closed, the thread that was supposed to read the socket kept spinning.
This is due to a mistake I made during the big rustup :-/
