### ISSUE TITLE
The example panics

### ISSUE THREAD

**Issue by MarkSwanson** [frewsxcv/tiny-http#66]
The sample README.md code panics:
    let server = tiny_http::ServerBuilder::new().build().unwrap();

fix:
    let server = tiny_http::ServerBuilder::new().with_random_port().build().unwrap();

or with_port(8080) ...

**Comment by tomaka** [comment]
So the reason for this is that by default it will use port 80, which is often forbidden for non-root users on Linux.

**Comment by frewsxcv** [comment]
@tomaka How do you feel about changing the port on the example to be 8000? Alternatively make the panic message more understandable than just `thread '<main>' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Os(13) }'`

**Comment by tomaka** [comment]
Yeah I'm totally fine with changing the port.
The fact that the error is obscure has to do with the stdlib (it's a generic i/o error), it's not a problem that we should tackle.
