### ISSUE TITLE
visibility issues

### ISSUE THREAD

**Issue by MarkSwanson** [frewsxcv/tiny-http#67]
in src/lib.rs:

mod client;
mod common;
mod request;
mod response;

should be

pub mod client;
pub mod common;
pub mod request;
pub mod response;

Rationale: so I can define a Request param like this:

...
   for request in server.incoming_requests() {
       test(&request)
    }
...

fn test (request: &tiny_http::request::Request) {
...
}

**Comment by tomaka** [comment]
Whats the problem with using just `tiny_http::Request`?

**Comment by MarkSwanson** [comment]
Apparently nothing :-)
Sorry for the noise.
