### ISSUE TITLE
what's the best way to test/match Method objects

### ISSUE THREAD

**Issue by GregDavidson** [frewsxcv/tiny-http#86]
I'm finding it awkward to construct and test Method objects.  I've found myself doing clumsy things like:

    let get_ = tiny_http::Method::from_str("GET").unwrap();
    let put_ = tiny_http::Method::from_str("PUT").unwrap();
    if req.get_method().eq(&get_) || req.get_method().eq(&put_) { ... }

is there a simpler way to construct and/or test values of type Method?

It seems to me that modelling type Method as an enum might be simpler, easier and more efficient.  Am I missing something?

Still loving tiny-http!  _Greg

**Comment by tomaka** [comment]
There's an `equiv` method, for example `if req.get_method().equiv("GET")`.
However I agree that a better API would be appreciated.

**Comment by GregDavidson** [comment]
Thanks, .equiv will be handy!  Do you think it's not too late to replace Method with an enum and do you think that would be better?  I'm rewriting an http server I originally wrote in C to provide an http interface to a PostgreSQL database.  In my C server I use enums for methods and for the standard request and respond header names (but adding an "other" case so I can pass along any non-standard header-names).

**Comment by frewsxcv** [comment]
I like the idea of making it an enum, what do you think @tomaka? Hyper does something similar

http://hyper.rs/hyper/hyper/method/enum.Method.html

**Comment by GregDavidson** [comment]
There are several good places where an enum might work better than a struct, including: request method, http version, request header names and response header names.  I love Rust's ability for enum constructors to take a parameter so that an enum type can be made open by providing an "other" constructor which takes a string value.

**Comment by miguelmartin75** [comment]
+1 for enums. Strings can also lead to typos with no compilation error to tell you made one; whereas if you spell an enumeration value wrong the compiler will spit an error at  you.

**Comment by GregDavidson** [comment]
I think that Hyper is repeating itself a bit here, specifically they're giving the same set of strings in their as_ref and from_str methods.  I think it would be easier to just make an array of the string values indexed by the integer value of the enums.  This pattern can be reused to similarly implement request header names and response header names.  I do think that request and response headers (and names) should be distinct types.

**Comment by frewsxcv** [comment]
Opened a PR that addresses this: #102

**Comment by frewsxcv** [comment]
Feedback is greatly appreciated ;)
