### ISSUE TITLE
break OR else in task_pool.rs

### ISSUE THREAD

**Issue by GregDavidson** [frewsxcv/tiny-http#93]
Just a little thing, to be fixed one way or the other:
task_pool.rs lines 110 - 116:

    let task;
    loop {
        if let Some(poped_task) = todo.pop_front() {
            task = poped_task;
            break;
        } else {

**Comment by frewsxcv** [comment]
Sorry, can you expand on what needs to be fixed for this issue? (or alternatively open a pull request)

**Comment by GregDavidson** [comment]
There is no unambiguous fix so I've left it to whoever loves this code to fix it.

Since the `break` makes the `else` redundant and vice versa, the fix is to either (1) get rid of the `break;` line or (2) get rid of the `else {` along with the matching `}`.

**Comment by frewsxcv** [comment]
Ah, I understand. Thanks for pointing it out!
