### ISSUE TITLE
Need public access to Method::as_str()

### ISSUE THREAD

**Issue by GregDavidson** [frewsxcv/tiny-http#97]
Is it intentional that Method::as_str() be private?

    impl Method {
        fn as_str(&self) -> &AsciiStr {
            match self { &Method(ref s) => s }
        }
    ... }

I'm attempting to send a Request to the database
and the ONLY part of the Request I can't seem to
get access to is the Method (except by writing it
to a buffer which is awfully inefficient).  Getting
it as an AsciiStr would be ideal.

_Greg

**Comment by frewsxcv** [comment]
Just published version 0.2.1 that includes this change
